### ISSUE TITLE
Empty content with sidenav collapsed and menu expanded

### ISSUE THREAD

**Issue by gmartinezk** [ng-matero/ng-matero#56]
Hi Zongbin, how are you.

First, thanks and congratulations for this awesome template.

The issue is about when sidenav is collapsed and the menu is expanded, the sidenav content sometimes appears empty, In part because the submenu items have no icons. This cause in my opinion, a loss of context. I attach some reference images

![Captura de pantalla de 2020-07-22 18-55-48](https://user-images.githubusercontent.com/1524616/88241239-24cb3000-cc4f-11ea-99b9-09eae7fc7880.png)
![Captura de pantalla de 2020-07-22 18-55-33](https://user-images.githubusercontent.com/1524616/88241244-25fc5d00-cc4f-11ea-861d-c6549251a227.png)

Do you have some tip to avoid this, some style/structure advice.

Thanks :slightly_smiling_face:

**Comment by nzbin** [comment]
The easiest way I think you can make menu collapsed when sidenav is collapsed. I will improve this in the future.

**Comment by Ricard01** [comment]
Well thats when the sidenav  is collapsed so i did this 

`
```css

.matero-sidenav-collapsed {
  .matero-sidenav {
	// rest remains same

	// Hides the height of the submenu 
    .submenu {
      height: 0; 
      overflow: hidden;
	
	//  Shows the submenu when the sidenav is not collapsed 
      &.active {
        height: auto; 
      }
    }

    &:hover {
      width: var(--sidenav-width);
      overflow: visible; //added

   
      .submenu{
        height: auto; // Shows de submenu in Hover
      }

    }
  }
}

```
